# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - main
pr:
  branches:
    exclude:
      - main 

pool:
  vmImage: ubuntu-latest

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: TestAndBuild
  displayName: Test and Build React Application
  jobs:
  - job: Test
    displayName: Run Tests
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run test -- --ci --reporters=default --reporters=jest-junit
      displayName: 'Install Dependencies and Run Tests'

    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '**/test-results.xml'
        testResultsFormat: 'JUnit'
        failTaskOnFailedTests: true
      displayName: 'Publish Test Results'

  - job: Build
    displayName: Build Application
    dependsOn: Test
    steps:
    - script: |
        npm install
        npm run build
      displayName: 'Build React Application'

- stage: ContaineriseAndPush
  displayName: Containerise and Push Image
  dependsOn: TestAndBuild
  jobs:
  - job: DockerBuild
    displayName: Build and Push Docker Image
    steps:
    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        containerRegistry: 'DockerHub'  
        repository: 'dohunwon/asd-group7-frontend'
        command: buildAndPush
        dockerfile: '**/Dockerfile'
        tags: |
          $(tag)

